import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import QuaryClient from "@/provider/QuaryClient";
import { Poppins } from "next/font/google";
import BotennicaChatbot from "@/temp";
const inter = Poppins({ subsets: ["latin"], weight: ["400", "500", "600", "700", "800", "900"] });

export const metadata: Metadata = {
  applicationName: "Nexora ",
  title: "Nexora",
  description: "Generated by Nexora",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}   >
        <QuaryClient >
          <Toaster position="top-right"
            reverseOrder={false} />
          <div className=" relative w-full min-h-screen ">
            {children}
          </div>
          <BotennicaChatbot />
        </QuaryClient>


        <script
          id="Nexora-widget"
          src="https://nexora.bishal.online/widget.js"
          data-server-url="https://nexora.bishal.online"
          data-site-id="Vishal B_web_collection1784816685483"
          data-unique-id="cmrxlrstw0001jj04poq79zer"
          data-welcome-message="Hello! How can I assist you today?"
          data-header-title="Nexora AI"
          data-button-label="Ask Nexora"
          data-button-color="#00612f"
          data-button-text-color="#ffffff"
          data-button-position="right"
          data-button-border-radius="30"
          data-window-width="400"
          data-window-height="500"
          data-primary-color="#00612f"
          data-theme="light"
        ></script>
      </body>
    </html>
  );
}
